### ISSUE TITLE
Crash to desktop after first frame is rendered when chimera's font override is disabled

### ISSUE THREAD

**Issue by LivingFray** [MangoFizz/balltze#5]
## Describe the bug
Halo CE crashes almost immediately upon launching. It gets past the loading splash screen, but upon hitting the main menu it renders  one frame with the UI and a black background before closing. This doesn't happen if I uninstall balltze or downgrade to v0.2.1

### Steps to reproduce
Launch haloce.exe with just chimera + balltze installed
Change enabled=1 to enabled=0 under [font_override] in chimera.ini

### Expected behavior
Game doesn't crash

### Environment
 - Installed mods: None
 - Win10, game installed to E: drive.

### Additional context
I installed the mod manually (copy dll into mods folder, copy data folder into My Games/Halo CE). 

balltze.log:
```
2025-01-07 23:29:25 INFO [Balltze] loading client...
2025-01-07 23:29:25 INFO [Balltze] Initializing plugins...
2025-01-07 23:29:25 INFO [Balltze] initialized successfully!
2025-01-07 23:29:27 INFO [Balltze] Preparing to load map maps\ui.map
2025-01-07 23:29:27 DEBUG [Balltze] Reading tag data from loaded map...
2025-01-07 23:29:27 INFO [Balltze] Initializing virtual tag data...
2025-01-07 23:29:27 INFO [Balltze] Importing tag data from other maps...
2025-01-07 23:29:27 DEBUG [Balltze] Updating tag data header...
2025-01-07 23:29:27 INFO [Balltze] Allocating model data buffer for secondary maps...
2025-01-07 23:29:27 DEBUG [Balltze] First tick
```

**Comment by MangoFizz** [comment]
Hi! I'm sorry you're having issues with Balltze. Are you using the latest release or did you build it from source?

**Comment by LivingFray** [comment]
I downloaded the latest release from the releases tab

**Comment by MangoFizz** [comment]
Okay try again with the one I just uploaded to releases. We released it in our package manager but I forgot to publish it here X_x

**Comment by LivingFray** [comment]
Thanks for updating the releases. Unfortunately that didn't fix it, but I have tracked down the cause to disabling [font_override] in chimera.ini. (Sorry I forgot to mention that in the initial bug report, I copied chimera + its ini file from my vr install and forgot I had changed it)

**Comment by MangoFizz** [comment]
Thanks for reporting this, there was a case I wasn't handling when Chimera's widescreen fix was disabled. I fixed it on https://github.com/MangoFizz/balltze/releases/tag/v1.3.1

**Comment by MangoFizz** [comment]
I think it showed up when you disabled the font override because it forces the widescreen fix to be enabled, so when you disabled it, since you didn't explicitly enable it with its command, it was disabled as well.

**Comment by LivingFray** [comment]
That looks like its fixed it. Thanks for the quick responses.
